### ISSUE TITLE
Wrong Department ID in emplyees example table?

### ISSUE THREAD

**Issue by michel-steuwer** [brownplt/B2T2#31]
Hi,

the `employees` table at: https://github.com/brownplt/B2T2/blob/main/ExampleTables.md contains the value `32` as a Department ID which is not present in the `departments` table. This is not the case in the linked source: https://en.wikipedia.org/wiki/Join_(SQL) where the `32` is a `33`.

I wanted to check if this is a deliberate choice (and if so, what the rationale is) or a mistake.

I stumbled across this when my prototype implementation reported this as a type error.

**Comment by bennn** [comment]
The `32` is indeed a typo. Thanks for catching it!

We plan to fix the typo, release a new version of B2T2, and notify other contributors.

But first, would you please fix the typo locally and keep working on your prototype implementation? We're all very impressed that your prototype caught this typo as a type error --- it's a kind of error we hadn't imagined! And it makes us wonder whether you'll find other errors further down in the API or in the example programs & errors. Ideally we'd like to fix those all together before notifying people.
