### ISSUE TITLE
Clarify license terms?

### ISSUE THREAD

**Issue by apaszke** [brownplt/B2T2#32]
I'd find it very convenient to use snippets of text and code from this repo elsewhere, but at the moment the terms of use are a bit unclear because the license is left unspecified. Could you please add a LICENSE file to clarify the rules under which other can build upon this project? Thanks!

**Comment by shriram** [comment]
Good point, we will do that. We're a bit under with a big deadline this
week, so expect us to handle this next week.

**Comment by shriram** [comment]
Thanks for bringing this up. We've committed [3c259b23dab8a83da360d0377204128efe8b7ccd] a license. Hopefully MIT works.
