### ISSUE TITLE
Table API document uses a subTable function that it doesn't define

### ISSUE THREAD

**Issue by apaszke** [brownplt/B2T2#33]
A quick search indicates that it [does appear in the `src/API-origin.md` file](https://github.com/brownplt/B2T2/blob/02537f5495275c6b177b7adbd9fc5163852067db/src/API-origin.md#subtable--t1table--rowselectorseq--columnselectorseq---t2table), but it seems to be missing from `TableAPI.md`.

**Comment by LuKC1024** [comment]
Hi Adam,

Thanks for catching this. We will add `subTable` as an assumption at the top of `TableAPI.md` (because it can be encoded as a composition of `selectRows` and `selectColumns`).

**Comment by bennn** [comment]
https://github.com/brownplt/B2T2/commit/9fd2bb9f4fa84e730e68524e527836789bcf2df7
