### ISSUE TITLE
crossJoin example references undefined "subTable()" function

### ISSUE THREAD

**Issue by eerivera** [brownplt/B2T2#41]
In the description for `crossJoin`, `petiteJelly` is constructed via a call to `subTable`. However, `subTable` is not defined (at least not in TableAPI.md).

**Comment by LuKC1024** [comment]
Thanks for the feedback! This is a known issue (#33). Our reply there is quoted below:

> We will add subTable as an assumption at the top of `TableAPI.md` (because it can be encoded as a composition of `selectRows` and `selectColumns`).
